# Generated by Django 5.1.5 on 2025-01-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.IntegerField()),
                ('output', models.IntegerField()),
                ('time_computed', models.DateTimeField(null=True)),
            ],
        ),
    ]
