# Generated by Django 5.1.6 on 2025-04-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='test_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
