# Generated by Django 5.1.5 on 2025-04-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsession',
            name='state',
        ),
        migrations.AddField(
            model_name='testsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
