# Generated by Django 5.1.6 on 2025-02-28 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.TextField()),
                ('latency', models.FloatField()),
                ('is_correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('stats_id', models.AutoField(primary_key=True, serialize=False)),
                ('avg_latency', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('total_tests', models.IntegerField()),
                ('total_responses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stimuli',
            fields=[
                ('stim_id', models.AutoField(primary_key=True, serialize=False)),
                ('stimulus', models.TextField()),
                ('correct_response', models.TextField()),
                ('span', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Computed',
        ),
        migrations.AddField(
            model_name='response',
            name='stim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.stimuli'),
        ),
        migrations.AddField(
            model_name='response',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.testsession'),
        ),
    ]
