# Generated by Django 5.1.5 on 2025-04-10 21:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_remove_testsession_state_testsession_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='test_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
