# Generated by Django 5.1.6 on 2025-04-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_response_statistics_stimuli_testsession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='latency',
        ),
        migrations.AddField(
            model_name='response',
            name='latencies',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='avg_latency',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='language',
            field=models.TextField(default='en'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='state',
            field=models.TextField(default='ready'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='stimuli_order',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='is_correct',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='avg_latency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_responses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
