# Generated by Django 5.1.5 on 2025-04-09 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_testsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
